# Generated by Django 3.0.4 on 2020-03-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100, verbose_name='organization')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('responsibilities', models.TextField(verbose_name='responsibilities')),
                ('started_work', models.DateTimeField(verbose_name='started_work')),
                ('finished_work', models.DateTimeField(verbose_name='finished_work')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PlaceOfWork')),
            ],
        ),
    ]
