# Generated by Django 3.0.3 on 2020-04-03 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeofwork',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='description'),
            preserve_default=False,
        ),
    ]
