# Generated by Django 3.0.3 on 2020-06-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_placeofwork_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='resume/', verbose_name='photo')),
                ('salutation', models.CharField(max_length=200, verbose_name='salutation')),
                ('description', models.TextField(verbose_name='description')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('reward', models.ImageField(upload_to='resume/', verbose_name='reward')),
            ],
        ),
    ]
