# Generated by Django 3.0.3 on 2020-06-11 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_myinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinformation',
            name='reward',
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_img', models.ImageField(upload_to='resume/', verbose_name='reward')),
                ('description', models.TextField(verbose_name='description')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.MyInformation')),
            ],
        ),
    ]
