# Generated by Django 3.0.3 on 2020-06-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200611_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='person',
        ),
        migrations.DeleteModel(
            name='MyInformation',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
