# Generated by Django 3.0.3 on 2020-06-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200611_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('photo', models.ImageField(upload_to='resume/', verbose_name='photo')),
                ('salutation', models.CharField(max_length=200, verbose_name='salutation')),
                ('description', models.TextField(verbose_name='description')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_img', models.ImageField(upload_to='resume/', verbose_name='reward')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.MyInformation')),
            ],
        ),
    ]
