# Generated by Django 3.0.3 on 2020-06-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_myinformation_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyContact',
        ),
    ]
