# Generated by Django 3.0.6 on 2020-08-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_delete_mycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('picture', models.ImageField(upload_to='project/', verbose_name='picture')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('url', models.CharField(max_length=100, unique=True, verbose_name='url')),
            ],
        ),
    ]
